# Docker-compose
# MySQl + Node(React) + Node(Express)
version: '3'
# Volumes
volumes:
  database_data:
    driver: local
# Services
services:
  # MySQL
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DB: "public"
  # server
  server:
    image: node:latest
    volumes:
      - ./server:/usr/src/app/server
    working_dir: /usr/src/app/server
    command: bash -c "npm install && npm run start"
    ports:
      - "5000:5000"
    links:
      - mysql
  # client
  client:
    image: node:latest
    volumes:
      - ./client:/usr/src/app/client
    working_dir: /usr/src/app/client
    command: bash -c "npm install && npm start"
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    links:
      - server